version: "3"
services:
  backend:
    build: ./backend
    container_name: 'mongo_api_tp5'
    command: sh -c 'npm install; npm run dev'
    ports:
      - '4000:4000'
    volumes:
      - /home/tomasbidegain/Tomas/Facultad/4to AÑO/bbdd-nsql/TP5/backend:/backend
    depends_on:
      - "mongo-db"

  mongo-db:
    container_name: 'dbmongo_tp5'
    image: mongo
    expose:
      - 27017
    ports:
      - "27017:27017"

  frontend:
    build: ./frontend
    container_name: 'mongo_api_frontend_tp5'
    image: node:16.20.0-alpine3.16
    command: sh -c 'npm install; npm start'
    ports:
      - '3000:3000'
    volumes:
      - /home/tomasbidegain/Tomas/Facultad/4to AÑO/bbdd-nsql/TP5/frontend:/frontend
    depends_on:
      - "backend"
    stdin_open: true
    tty: true